### ISSUE TITLE
Crash with WorldEdit, java.lang.NoClassDefFoundError: org.apache.logging.log4j.util.ReflectionUtil

### ISSUE THREAD

**Issue by Axelandre42** [EngineHub/WorldEdit#1398]
**Versions**

WorldEdit version: 7.2.0-beta-01 (fabric)
Platform version: Minecraft 1.16.1, Fabric Loader 0.8.8, MultiMC 5

**Describe the bug**

Crash while loading world.

**To Reproduce**

1. Install MultiMC 5,
2. Create an 1.16.1 instance and add Fabric to the instance,
3. Add WorldEdit,
4. Start the game, and load a world,
5. Crash occurs.

**Expected behavior**

No crashes.

**Screenshots**

None.

**Additional context**

Crash report: [crash-2020-06-28_11.06.59-server.txt](https://github.com/EngineHub/WorldEdit/files/4842098/crash-2020-06-28_11.06.59-server.txt)

**Comment by octylFractal** [comment]
This sounds like a MultiMC bug, because the normal launcher boots up fine. Can you try again with the normal launcher?

**Comment by wizjany** [comment]
can't reproduce on multimc either https://i.imgur.com/2vJO9dn.png https://i.imgur.com/xCa9MCZ.png

**Comment by wizjany** [comment]
closing unless we get more info (conflict with another mod maybe? would need a mod list).

**Comment by Lartza** [comment]
The exact same issue happens with Forge using HotSpot when creating a new world. Afaict it's because log4j-api-2.11.2.jar which is the library getting loaded, does not have ReflectionUtil anymore, it was removed in 2.9.x

**Comment by octylFractal** [comment]
are you reproducing this on the latest WorldEdit?

**Comment by Lartza** [comment]
7.2.3 yes. latest.log and crash report for good measure https://gist.github.com/Lartza/61604b09e1f49d2481c12b07d8bf50aa

**Comment by Napkin** [comment]
Just upgraded from worldedit-forge-mc1.16.3-7.2.2-dist.jar to worldedit-mod-7.2.3.jar and getting this error, too. Only on single player worlds, though. The dedicated server starts fine with 7.2.3 and the clients (with 7.2.3) have no issue joining.

Clients using Java8 as in OpenJDK 8u275-b01 or AdoptJDK 8u232-b09.
Server using Java8 as in AdoptJDK 8u232-b09.

Platform: Minecraft 1.16.5, Forge 36.0.42

Client crash in single player with 7.2.3: https://paste.ee/p/7aG4M
Client fine in single player with 7.2.2: https://paste.ee/p/PDBge

Thanks for this great mod!

**Comment by Sandriell** [comment]
Having this same issue on Forge

https://gist.github.com/Sandriell/a076a88d52148214d7f9e53f2e1b4377

WE: 7.2.3, Forge: 35.1.37

As above, no issue with client/dedicated server.

**Comment by joernott** [comment]
Still getting the error with World Edit 7.2.4, Forge 36.1.0 (and 36.1.1) and MultiMC 5 0.6.11-1430 running jdk-15.0.2 as well as jre1.8.0_281

**Comment by Lartza** [comment]
Can confirm. Forge 36.1.1, WorldEdit 7.2.4, still an issue https://gist.github.com/Lartza/05d12a66d6e708ec820e79064814a6c0

**Comment by me4502** [comment]
No one has seen this error without MultiMC so far, this is almost definitely a MultiMC bug, as it works on the vanilla launcher.

**Comment by Lartza** [comment]
Without knowing too much Java or especially mod programming, is it deliberate log4j on Forge is loaded as com.sk89q.worldedit-fabric.slf4j and not com.sk89q.worldedit-forge.slf4j after https://github.com/EngineHub/WorldEdit/commit/36f23bd29f7750c3cb4ebc12f52e444f46555e2f

And while I don't deny the notion it is true that this is so far the only mod that has this issue with MultiMC too

**Comment by me4502** [comment]
The thought is that MultiMC is using incorrect classloading order. Basically, the JVM loads classes as they are requested, the -fabric slf4j classes are never requested by the Forge mod, and should therefore never be loaded. It appears as though MultiMC is pre-emptively loading *all* classes, even ones that should not be loaded. As it hits the fabric classes first due to alphabetical ordering, those are the ones that are used.

This would affect anything that uses optional classes that are dependent on other systems. In this case, the -fabric classes are dependent on being bootstrapped by Fabric. It would also affect any other mod that optionally loads further functionality when in the presence of a different mod though, which is not uncommon.

**Comment by spannerman79** [comment]
No, this is **not** a MultiMC issue.

I just replicated this same issue using the Vanilla Launcher, using the Fabric Installer (god I forgotten how backwards things are using the Vanilla way are vs MultiMC).

```latest.log
[22:03:41] [main/INFO]: Loading for game Minecraft 1.16.1
[22:03:42] [main/INFO]: [FabricLoader] Loading 9 mods: fabric-lifecycle-events-v1@1.2.0+ffb68a873a, minecraft@1.16.1, fabric-networking-api-v1@1.0.0+4358fbc63a, java@8, fabric-events-interaction-v0@0.4.1+6a2618f53a, fabric-command-api-v1@1.0.9+6a2618f53a, fabricloader@0.11.3, worldedit@7.2.2+fc3c499, fabric-api-base@0.2.0+ab87788d3a
[22:03:42] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/home/spannerman/.minecraft/libraries/net/fabricmc/sponge-mixin/0.9.2+mixin.0.8.2/sponge-mixin-0.9.2+mixin.0.8.2.jar Service=Knot/Fabric Env=CLIENT
[22:03:44] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', name='PROD'
[22:03:44] [main/INFO]: Setting user: Spanner_Man
[22:03:44] [main/INFO]: WorldEdit for Fabric (version 7.2.2+fc3c499) is loaded
[22:03:44] [main/INFO]: Backend library: LWJGL version 3.2.2 build 10
[22:03:45] [main/WARN]: ERROR : Couldn't load Narrator library : Unable to load library 'fliteWrapper': Native library (linux-x86-64/libfliteWrapper.so) not found in resource path (/home/spannerman/.minecraft/libraries/net/fabricmc/tiny-mappings-parser/0.2.2.14/tiny-mappings-parser-0.2.2.14.jar:/home/spannerman/.minecraft/libraries/net/fabricmc/sponge-mixin/0.9.2+mixin.0.8.2/sponge-mixin-0.9.2+mixin.0.8.2.jar:/home/spannerman/.minecraft/libraries/net/fabricmc/tiny-remapper/0.3.0.70/tiny-remapper-0.3.0.70.jar:/home/spannerman/.minecraft/libraries/net/fabricmc/access-widener/1.0.0/access-widener-1.0.0.jar:/home/spannerman/.minecraft/libraries/net/fabricmc/fabric-loader-sat4j/2.3.5.4/fabric-loader-sat4j-2.3.5.4.jar:/home/spannerman/.minecraft/libraries/com/google/jimfs/jimfs/1.2-fabric/jimfs-1.2-fabric.jar:/home/spannerman/.minecraft/libraries/org/ow2/asm/asm/9.1/asm-9.1.jar:/home/spannerman/.minecraft/libraries/org/ow2/asm/asm-analysis/9.1/asm-analysis-9.1.jar:/home/spannerman/.minecraft/libraries/org/ow2/asm/asm-commons/9.1/asm-commons-9.1.jar:/home/spannerman/.minecraft/libraries/org/ow2/asm/asm-tree/9.1/asm-tree-9.1.jar:/home/spannerman/.minecraft/libraries/org/ow2/asm/asm-util/9.1/asm-util-9.1.jar:/home/spannerman/.minecraft/libraries/net/fabricmc/intermediary/1.16.1/intermediary-1.16.1.jar:/home/spannerman/.minecraft/libraries/net/fabricmc/fabric-loader/0.11.3/fabric-loader-0.11.3.jar:/home/spannerman/.minecraft/libraries/com/mojang/patchy/1.1/patchy-1.1.jar:/home/spannerman/.minecraft/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar:/home/spannerman/.minecraft/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar:/home/spannerman/.minecraft/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar:/home/spannerman/.minecraft/libraries/com/ibm/icu/icu4j/66.1/icu4j-66.1.jar:/home/spannerman/.minecraft/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar:/home/spannerman/.minecraft/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar:/home/spannerman/.minecraft/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar:/home/spannerman/.minecraft/libraries/com/google/guava/guava/21.0/guava-21.0.jar:/home/spannerman/.minecraft/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar:/home/spannerman/.minecraft/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar:/home/spannerman/.minecraft/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar:/home/spannerman/.minecraft/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar:/home/spannerman/.minecraft/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar:/home/spannerman/.minecraft/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar:/home/spannerman/.minecraft/libraries/com/mojang/datafixerupper/3.0.25/datafixerupper-3.0.25.jar:/home/spannerman/.minecraft/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar:/home/spannerman/.minecraft/libraries/com/mojang/authlib/1.6.25/authlib-1.6.25.jar:/home/spannerman/.minecraft/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar:/home/spannerman/.minecraft/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar:/home/spannerman/.minecraft/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar:/home/spannerman/.minecraft/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar:/home/spannerman/.minecraft/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar:/home/spannerman/.minecraft/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar:/home/spannerman/.minecraft/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar:/home/spannerman/.minecraft/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar:/home/spannerman/.minecraft/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar:/home/spannerman/.minecraft/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar:/home/spannerman/.minecraft/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar:/home/spannerman/.minecraft/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar:/home/spannerman/.minecraft/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar:/home/spannerman/.minecraft/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar:/home/spannerman/.minecraft/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar:/home/spannerman/.minecraft/versions/fabric-loader-0.11.3-1.16.1/fabric-loader-0.11.3-1.16.1.jar)
[22:03:45] [main/INFO]: Reloading ResourceManager: Default
[22:03:46] [main/INFO]: OpenAL initialized.
[22:03:46] [main/INFO]: Sound engine started
[22:03:47] [main/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/blocks.png-atlas
[22:03:47] [main/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[22:03:47] [main/INFO]: Created: 1024x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[22:03:47] [main/INFO]: Created: 1024x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[22:03:47] [main/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[22:03:47] [main/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[22:03:47] [main/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[22:03:47] [main/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[22:03:47] [main/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[22:03:47] [main/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[22:04:42] [main/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[22:04:42] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[22:04:42] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[22:04:42] [main/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[22:04:42] [main/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[22:04:42] [main/INFO]: Reloading ResourceManager: Default
[22:04:42] [main/INFO]: Loaded 7 recipes
[22:04:42] [main/INFO]: Loaded 927 advancements
[22:04:42] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', name='PROD'
[22:04:42] [Server thread/INFO]: Starting integrated minecraft server version 1.16.1
[22:04:42] [Server thread/INFO]: Generating keypair
[22:04:44] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[22:04:44] [main/INFO]: Preparing spawn area: 0%
[22:04:45] [main/INFO]: Preparing spawn area: 2%
[22:04:45] [main/INFO]: Preparing spawn area: 6%
[22:04:46] [main/INFO]: Preparing spawn area: 15%
[22:04:46] [main/INFO]: Preparing spawn area: 22%
[22:04:47] [main/INFO]: Preparing spawn area: 29%
[22:04:47] [main/INFO]: Preparing spawn area: 36%
[22:04:48] [main/INFO]: Preparing spawn area: 45%
[22:04:48] [main/INFO]: Preparing spawn area: 52%
[22:04:49] [main/INFO]: Preparing spawn area: 59%
[22:04:49] [main/INFO]: Preparing spawn area: 66%
[22:04:50] [main/INFO]: Preparing spawn area: 72%
[22:04:50] [main/INFO]: Preparing spawn area: 80%
[22:04:51] [main/INFO]: Preparing spawn area: 87%
[22:04:51] [main/INFO]: Preparing spawn area: 94%
[22:04:51] [main/INFO]: Time elapsed: 7283 ms
[22:04:51] [Server thread/INFO]: Got request to register class com.sk89q.worldedit.fabric.FabricPlatform with WorldEdit [com.sk89q.worldedit.extension.platform.PlatformManager@6da2a7be]
[22:04:51] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoSuchMethodError: net.minecraft.server.MinecraftServer.method_30611()Lnet/minecraft/class_5455;
	at com.sk89q.worldedit.fabric.FabricWorldEdit.setupRegistries(FabricWorldEdit.java:188) ~[worldedit-fabric-mc1.16.3-7.2.2-dist.jar:?]
	at com.sk89q.worldedit.fabric.FabricWorldEdit.onStartServer(FabricWorldEdit.java:216) ~[worldedit-fabric-mc1.16.3-7.2.2-dist.jar:?]
	at net.minecraft.server.MinecraftServer.handler$zzk000$afterSetupServer(MinecraftServer.java:2229) ~[intermediary-fabric-loader-0.11.3-1.16.1.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:653) ~[intermediary-fabric-loader-0.11.3-1.16.1.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:256) ~[intermediary-fabric-loader-0.11.3-1.16.1.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
[22:04:51] [Server thread/ERROR]: This crash report has been saved to: /home/spannerman/.minecraft/crash-reports/crash-2021-03-21_22.04.51-server.txt
[22:04:51] [Server thread/INFO]: Unregistering com.sk89q.worldedit.fabric.FabricPlatform from WorldEdit
[22:04:51] [Server thread/INFO]: Stopping server
[22:04:51] [Server thread/INFO]: Saving players
[22:04:51] [Server thread/INFO]: Saving worlds
[22:04:51] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld

```

Issue is Worldedit itself, not MultiMC

**Comment by me4502** [comment]
That error is entirely unrelated - and due to you running a mismatched Minecraft and WorldEdit version

**Comment by kb-1000** [comment]
This might be related to ForgeWrapper.
What version of log4j is on classpath when you run it with the vanilla launcher?
With MultiMC/ForgeWrapper, it appears to be 2.11.2.

**Comment by phit** [comment]
@kb-1000 I tested it on Technic launcher earlier today which also uses ForgeWrapper and could not reproduce the issue, so its something MultiMC is doing

**Comment by kb-1000** [comment]
Just checked, log4j is both defined in net.minecraft/1.16.5.json and net.minecraftforge/36.0.42.json.
In net.minecraft/1.16.5.json, the version is 2.8.1. In net.minecraftforge/36.0.42.json, the version is 2.11.2.

**Comment by jamierocks** [comment]
My guess here is that with the Vanilla launcher both versions are on the classpath and the `ReflectionUtil` is loaded from the old version of log4j (possibly depending on order, everything is loaded from that version).

The trouble on MultiMC is by design - it will only allow one artefact to be present on the classpath (https://github.com/MultiMC/MultiMC5/blob/5400d4e61389694597381f360e0462932d33bfe1/api/logic/minecraft/LaunchProfile.cpp#L154-L158). It will specifically use the latest version of the library.

**Comment by jamierocks** [comment]
I did some digging to verify that MultiMC's data wasn't at fault here, and indeed Forge does upgrade log4j2 in their metadata (see https://gist.github.com/jamierocks/d2737b2d478feb9866f7a9fc90caef51#file-version-json-L240-L261).

I assume Gradle is clever enough to use a single artefact (and the latest), does this work in a Forge development environment?

**Comment by octylFractal** [comment]
Yes, we figured that out a _long_ time ago, this is already fixed as indicated by the fact I closed it with a commit.

In fact this will become even _more_ solved with #1715 merge.

**Comment by phit** [comment]
The last comments here from 6 days ago by me4502 indicated otherwise, also its not fixed in 7.2.4, the current latest release.
Anyway now I see there's a newer issue https://github.com/EngineHub/WorldEdit/issues/1709 where you seemed to have figured it out 5 days ago. I wouldn't call that a _long_ time ago and people coming from MultiMC were still under the impression you are still blaming the launcher, since that new issue or PR was never posted here, even though there was an ongoing discussion.

**Comment by zhro** [comment]
I have this same error trying to use `worldedit-bukkit-7.2.6-SNAPSHOT-dist.jar` with the latest Spigot 1.17 snapshot.

```
2021-06-12 06:23:21 [ERROR] Could not load 'plugins/WorldEdit-Bukkit-7.2.2.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: org/apache/logging/log4j/util/ReflectionUtil
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:149) ~[spigot-1.17.jar:3121-Spigot-66f9d3c-eeae1b1]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:394) ~[spigot-1.17.jar:3121-Spigot-66f9d3c-eeae1b1]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:301) ~[spigot-1.17.jar:3121-Spigot-66f9d3c-eeae1b1]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.loadPlugins(CraftServer.java:384) ~[spigot-1.17.jar:3121-Spigot-66f9d3c-eeae1b1]
        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:232) ~[spigot-1.17.jar:3121-Spigot-66f9d3c-eeae1b1]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:986) ~[spigot-1.17.jar:3121-Spigot-66f9d3c-eeae1b1]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307) ~[spigot-1.17.jar:3121-Spigot-66f9d3c-eeae1b1]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NoClassDefFoundError: org/apache/logging/log4j/util/ReflectionUtil
        at com.sk89q.worldedit.log4jbridge.Log4jLoggerFactory.getContext(Log4jLoggerFactory.java:42) ~[?:?]
        at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:47) ~[spigot-1.17.jar:3121-Spigot-66f9d3c-eeae1b1]
        at com.sk89q.worldedit.log4jbridge.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:29) ~[?:?]
        at com.sk89q.worldedit.slf4j.LoggerFactory.getLogger(LoggerFactory.java:358) ~[?:?]
        at com.sk89q.worldedit.slf4j.LoggerFactory.getLogger(LoggerFactory.java:383) ~[?:?]
        at com.sk89q.worldedit.bukkit.WorldEditPlugin.<clinit>(WorldEditPlugin.java:113) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:466) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:67) ~[spigot-1.17.jar:3121-Spigot-66f9d3c-eeae1b1]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:145) ~[spigot-1.17.jar:3121-Spigot-66f9d3c-eeae1b1]
        ... 7 more
Caused by: java.lang.ClassNotFoundException: org.apache.logging.log4j.util.ReflectionUtil
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:142) ~[spigot-1.17.jar:3121-Spigot-66f9d3c-eeae1b1]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[spigot-1.17.jar:3121-Spigot-66f9d3c-eeae1b1]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        at com.sk89q.worldedit.log4jbridge.Log4jLoggerFactory.getContext(Log4jLoggerFactory.java:42) ~[?:?]
        at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:47) ~[spigot-1.17.jar:3121-Spigot-66f9d3c-eeae1b1]
        at com.sk89q.worldedit.log4jbridge.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:29) ~[?:?]
        at com.sk89q.worldedit.slf4j.LoggerFactory.getLogger(LoggerFactory.java:358) ~[?:?]
        at com.sk89q.worldedit.slf4j.LoggerFactory.getLogger(LoggerFactory.java:383) ~[?:?]
        at com.sk89q.worldedit.bukkit.WorldEditPlugin.<clinit>(WorldEditPlugin.java:113) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:466) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:67) ~[spigot-1.17.jar:3121-Spigot-66f9d3c-eeae1b1]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:145) ~[spigot-1.17.jar:3121-Spigot-66f9d3c-eeae1b1]
        ... 7 more
```

**Comment by octylFractal** [comment]
that is very clearly not 7.2.6 snapshot. read the file name.
